name: OpenNebula Smoke Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  smoke-tests:
    runs-on: self-hosted

    steps:
      - name: Install and Run tests
        run: apt install -y build-essential
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install rubocop
        run: gem install rubocop
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Smoke Tests
        run: $GITHUB_WORKSPACE/share/smoke_tests/smoke_tests.sh
  test_arm64: 
     runs-on: self-hosted
     steps:
      - uses: actions/checkout@v2
      - name: Install and Run tests
        run: apt install -y build-essential
      - name: install node
        run: |
           curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
           apt install -y nodejs
           apt-get -y install ruby-full
           gem install rubocop
           npm install eslint-plugin-import@latest --save-dev
           npm i -D eslint @typescript-eslint/eslint-plugin
           ./share/smoke_tests/smoke_tests.sh
                
