name: OpenNebula Smoke Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  smoke-tests:
    runs-on: self-hosted

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run Smoke Tests
        run: $GITHUB_WORKSPACE/share/smoke_tests/smoke_tests.sh
  test_arm64: 
     runs-on: self-hosted
     steps:
      - uses: actions/checkout@v2
      - name: Install and Run tests
        run: |
                sudo apt-get update -y
                sudo apt install -y build-essential
                sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
                sudo apt install -y nodejs
                sudo apt-get -y install ruby-full
                sudo gem install rubocop
                sudo npm install eslint-plugin-import@latest --save-dev
                sudo npm i -D eslint @typescript-eslint/eslint-plugin
                sudo ./share/smoke_tests/smoke_tests.sh
                
